var DetailsPageJs=new Class.create;
DetailsPageJs.prototype=Object.extend(new BPCPageJs,{_item:null,_readOnlyMode:!1,_dirty:!1,_getFormGroup:function(a,c,d){var b;b=new Element("div",{"class":"form-group form-group-sm"});a&&("string"!==typeof a||"string"===typeof a&&!a.blank())&&b.insert({bottom:(new Element("label")).update(a)});b.insert({bottom:c.addClassName(!0===d?"":"form-control")});return b},refreshParentWindow:function(){var a,c,d;if(parent.window)return a=parent.window,(c=$(a.document.body).down("#"+a.pageJs.resultDivId+" .item_row[item_id="+
this._item.id+"]"))?(c.replace(a.pageJs._getResultRow(this._item)),c.hasClassName("success")||c.addClassName("success")):$(a.document.body).down("#"+a.pageJs.resultDivId+" #item-list-body")&&($(a.document.body).down("#"+a.pageJs.resultDivId+" #item-list-body").insert({top:a.pageJs._getResultRow(this._item)}),(d=$(a.document.body).down("#"+a.pageJs.totalNoOfItemsId))&&d.update(parseInt(d.innerHTML)+1)),this},_getSaveBtn:function(){var a={me:this};a.me._refreshDirty();if(!a.me._containerIds||!a.me._containerIds.saveBtn)return a.me;
a.container=$(a.me._containerIds.saveBtn);if(!a.container)return a.me;a.save=(new Element("i")).addClassName("btn btn-success btn-md").update("Save").observe("click",function(c){a.btn=$(this);a.data=a.me.collectData();if(!0===a.btn.readAttribute("disabled")||"disabled"===a.btn.readAttribute("disabled")||null===a.data||null===a.data)return a.me;a.me._item&&a.me._item.id&&(a.data.id=a.me._item.id);a.me.saveItem(a.input,a.data)});a.cancel=(new Element("i")).addClassName("btn btn-default btn-md").update("Cancel").observe("click",
function(c){a.me.closeFancyBox()});a.container.update("").addClassName("col-xs-12").insert({bottom:a.me._getFormGroup(a.title,a.save).addClassName("col-xs-6")}).insert({bottom:a.me._getFormGroup(a.title,a.cancel).addClassName("pull-right col-xs-6")});!1===a.me._dirty&&a.save.hide();return a.me},collectData:function(){return this._collectFormData($(this.getHTMLID("itemDiv")),"save-item")},closeFancyBox:function(){parent.jQuery&&parent.jQuery.fancybox?parent.jQuery.fancybox.close():location.reload();
return this},_getDatePickerDiv:function(a,c,d,b,g,m,l){var h,e,k,f,n;h=this;b=b||h.ucfirst(a);e=!0===g;l=l||"col-xs-12";m=m||"DD/MM/YYYY";d.id||h._signRandID(d);if(d=$(d.id)){k=(new Element("input")).writeAttribute({required:e,"save-item":a,dirty:!1}).setValue(c||"");d.update(h._getFormGroup(b,k).addClassName(l));if("function"!==typeof jQuery(document).datetimepicker)return h;h._signRandID(k);f=jQuery("#"+k.id).datetimepicker({format:m,showClear:!g});f.on("dp.change keyup",function(b){f.data("DateTimePicker")&&
f.data("DateTimePicker").date()?(n=f.data("DateTimePicker").date().local().format("YYYY-MM-DDThh:mm:ss"),a.endsWith("from")&&n.format("YYYY-MM-DDT00:00:00"),a.endsWith("to")&&n.format("YYYY-MM-DDT23:59:59")):n="";k.writeAttribute("dirty",c!==n);h._refreshDirty()._getSaveBtn()});return h}},_getInputDiv:function(a,c,d,b,g,m,l,h){var e,k,f;e=this;b=b||e.ucfirst(a);g=!0===g;m=m||"col-xs-12";k=!0===l;l=h||"";if(!d)return e;d.id||e._signRandID(d);d=$(d.id);if(!d)return e;f=(new Element("input")).writeAttribute({required:g,
"save-item":a,placeholder:""!==l?l:b,dirty:!1}).setValue(c||"").observe("change",function(a){!0===k&&f.setValue(e.getValueFromCurrency($F(f)))}).observe("keyup",function(a){f.writeAttribute("dirty",c!==(!0===k?e.getValueFromCurrency($F(f)):$F(f)));e._refreshDirty()._getSaveBtn()});d.update(e._getFormGroup(b,f).addClassName(m));return e},_refreshDirty:function(){var a;a=!1;$(this.getHTMLID("itemDiv")).getElementsBySelector("[save-item]").each(function(c){!1!==a||!0!==c.readAttribute("dirty")&&"true"!==
c.readAttribute("dirty")&&"dirty"!==c.readAttribute("dirty")||(a=!0)});this._dirty=a;return this},_getSelect2Div:function(a,c,d,b,g,m,l,h){var e,k,f,n;e=this;g=g||e.ucfirst(c);m=!0===m;l=l||null;h=h||"col-xs-12";b.id||e._signRandID(b);if(b=$(b.id))return c=(new Element("input")).writeAttribute("required",m).writeAttribute("placeholder","Please select a "+a).writeAttribute("save-item",c),b.update(e._getFormGroup(g,c).addClassName(h)),e._signRandID(c),k=[],e._item&&e._item.id&&(Array.isArray(d)?d.each(function(a){k.push({id:a.id,
text:a.name,data:a})}):k=d),f=jQuery("#"+c.id).select2(l?l:{multiple:!0,allowClear:!0,width:"100%",ajax:{delay:250,url:"/ajax/getAll",type:"GET",data:function(b){return{searchTxt:"name like ?",searchParams:["%"+b+"%"],entityName:a,pageNo:1}},results:function(a,b,c){n=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){n.push({id:a.id,text:a.name,data:a})});return{results:n}}},cache:!0,escapeMarkup:function(a){return a}}),f.on("change",function(){f.attr("dirty",f.val()!==e._getNamesString(d,
"id",","));e._refreshDirty()._getSaveBtn()}),k&&f.select2("data",k),e},setItem:function(a){this._item=a;return this},saveItem:function(a,c,d){var b,g;b=this;a&&(b._signRandID(a),jQuery("#"+a.id).prop("disabled",!0));b._disableAll($(b.getHTMLID("itemDiv")));b.postAjax(b.getCallbackId("saveItem"),c,{onSuccess:function(a,c){try{(g=b.getResp(c,!1,!0))&&g.item&&g.item.id&&(b._item=g.item,"function"===typeof d&&d(g),b.closeFancyBox())}catch(h){b.showModalBox('<strong class="text-danger">ERROR:</strong>',
h),b._refreshDirty()._getSaveBtn()}},onComplete:function(){a&&jQuery("#"+a.id).prop("disabled",!1);b.refreshParentWindow()}});return b},_init:function(){return this},setPreData:function(a){a&&(this._preSetData=a);return this},bindAllEventNObjects:function(){return this},load:function(){this._init();$(this.getHTMLID("itemDiv")).addClassName("row");this._getInputDiv("name",this._item.name||"",$(this._containerIds.name),null,!0)._getInputDiv("description",this._item.description||"",$(this._containerIds.description))._getSaveBtn();
return this},_getCommentsDiv:function(){var a,c;a=$(this._containerIds.comments);c=new Element("div");a.insert({bottom:this._getFormGroup("Comments",c,!0).addClassName("col-md-12")});this._signRandID(c);(new CommentsDivJs(this,this._focusEntity,this._item.id))._setDisplayDivId(c.id).render();return this}});