var BPCPageJs=new Class.create;
BPCPageJs.prototype={modalId:"page_modal_box_id",_htmlIDs:{},_ajaxRequest:null,callbackIds:{},initialize:function(){},setCallbackId:function(a,c){this.callbackIds[a]=c;return this},getCallbackId:function(a){if(void 0===this.callbackIds[a]||null===this.callbackIds[a])throw"Callback ID is not set for:"+a;return this.callbackIds[a]},setHTMLID:function(a,c){this._htmlIDs[a]=c;return this},getHTMLID:function(a){return this._htmlIDs[a]},getFormGroup:function(a,c,b){var d;b=b||!1;d=(new Element("div")).addClassName("form-group");
a&&d.insert({bottom:a.addClassName("control-label")});c&&(!0===b&&c.addClassName("form-control"),d.insert({bottom:c}));return d},postAjax:function(a,c,b,d){this._ajaxRequest=new Prado.CallbackRequest(a,b);this._ajaxRequest.setCallbackParameter(c);a=d||3E4;3E4>a&&(a=3E4);this._ajaxRequest.setRequestTimeOut(a);this._ajaxRequest.dispatch();return this._ajaxRequest},abortAjax:function(){null!==this._ajaxRequest&&this._ajaxRequest.abort()},getResp:function(a,c,b){if(!0===(!0!==c?!1:!0))return a;if(a&&
a.isJSON()){a=a.evalJSON();if(0!==a.errors.size()){c="Error: \n\n"+a.errors.join("\n");if(!0===b)throw c;return alert(c)}return a.resultData}},getCurrency:function(a,c,b,d,f,g){var e,h;e=isNaN(b=Math.abs(b))?2:b;c=void 0==c?"$":c;d=void 0==d?".":d;f=void 0==f?",":f;b=0>a?"-":"";g=g||"%s%v";if("object"===typeof accounting&&"function"===typeof accounting.formatMoney)return accounting.formatMoney(a,c,e,f,d,g);g=parseInt(a=Math.abs(+a||0).toFixed(e))+"";h=3<(h=g.length)?h%3:0;return c+b+(h?g.substr(0,
h)+f:"")+g.substr(h).replace(/(\d{3})(?=\d)/g,"$1"+f)+(e?d+Math.abs(a-g).toFixed(e).slice(2):"")},getValueFromCurrency:function(a,c){var b,d;b=a||"";d=c||".";if(""===b)return b;if("object"===typeof accounting&&"function"===typeof accounting.unformat)return accounting.unformat(b,d);b=(b+"").replace(/\s*/g,"").replace(/\$/g,"").replace(/,/g,"");return b=/^-?\d*[\.]?\d+$/.exec(b)},keydown:function(a,c,b,d){d=d?d:13;if(!(a.which&&a.which==d||a.keyCode&&a.keyCode==d))return"function"===typeof b&&b(),!0;
"function"===typeof c&&c();return!1},getAlertBox:function(a,c){return(new Element("div",{"class":"alert alert-dismissible",role:"alert"})).insert({bottom:(new Element("button",{"class":"","data-dismiss":"alert"})).insert({bottom:(new Element("span",{"aria-hidden":"true"})).update("&times;")}).insert({bottom:(new Element("span",{"class":"sr-only"})).update("Close")})}).insert({bottom:(new Element("strong")).update(a)}).insert({bottom:c})},_signRandID:function(a){if(!a)return this;a.id||(a.id="input_"+
String.fromCharCode(65+Math.floor(26*Math.random()))+Date.now());return this},_markFormGroupError:function(a,c){var b={me:this};b.visible=a.visible();a.up(".form-group")&&(a.store("clearErrFunc",function(b){a.up(".form-group").removeClassName("has-error");jQuery("#"+a.id).tooltip("hide").tooltip("destroy").show()}).up(".form-group").addClassName("has-error"),b.me._signRandID(a),jQuery("#"+a.id).tooltip({trigger:"manual",placement:"auto",container:"body",placement:"bottom",html:!0,title:c,content:c}).tooltip("show"),
jQuery("#"+a.id).on("keyup change dp.change",function(){b.func=$(a).retrieve("clearErrFunc");"function"===typeof b.func&&b.func()}),b.visible||a.hide());return b.me},_collectFormData:function(a,c,b,d){var f,g,e,h,k,m,l;f=this;g={};e=!1;h=!0===d?!0:!1;$(a).getElementsBySelector("["+c+"]").each(function(a){k=b?a.readAttribute(b):null;m=a.readAttribute(c);!0!==h&&a.hasAttribute("required")&&$F(a).blank()&&(f._markFormGroupError(a,"This is requried"),e=!0);l="checkbox"!==a.readAttribute("type")?$F(a):
$(a).checked;if(a.hasAttribute("validate_currency")||a.hasAttribute("validate_number"))!0!==h&&null===f.getValueFromCurrency(l).match(/^(-)?\d+(\.\d{1,4})?$/)&&(f._markFormGroupError(a,a.hasAttribute("validate_currency")?a.readAttribute("validate_currency"):a.hasAttribute("validate_number")),e=!0),f.getValueFromCurrency(l);null!==k&&void 0!==k?(g[k]||(g[k]={}),g[k][m]=l):g[m]=l});return!0===e?null:g},showModalBox:function(a,c,b,d,f,g){var e;b=!0===b?!0:!1;g=!0===g?!0:!1;d=d||null;$(this.modalId)?
(e=jQuery("#"+this.modalId),f=e.find(".modal-dialog").removeClass("modal-sm").removeClass("modal-lg").addClass(!0===b?"modal-sm":"modal-lg"),e.find(".modal-title").html(a),e.find(".modal-body").html(c),0<e.find(".modal-footer").length?null!==d?e.find(".modal-footer").html(d):e.find(".modal-footer").remove():null!==d&&jQuery('<div class="modal-footer"></div>').html(d).appendTo(f.find(".modal-content"))):(a=(new Element("div",{id:this.modalId,"class":"modal",tabindex:"-1",role:"dialog","aria-hidden":"true",
"aria-labelledby":"page-modal-box"})).insert({bottom:(new Element("div",{"class":"modal-dialog "+(!0===b?"modal-sm":"modal-lg")})).insert({bottom:(new Element("div",{"class":"modal-content"})).insert({bottom:(new Element("div",{"class":"modal-header"})).insert({bottom:(new Element("div",{"class":"close",type:"button","data-dismiss":"modal"})).insert({bottom:(new Element("span",{"aria-hidden":"true"})).update("&times;")})}).insert({bottom:(new Element("strong",{"class":"modal-title"})).update(a)})}).insert({bottom:(new Element("div",
{"class":"modal-body"})).update(c)}).insert({bottom:null===d?"":(new Element("div",{"class":"modal-footer"})).update(d)})})}),$$("body")[0].insert({bottom:a}),e=jQuery("#"+this.modalId),!0===g&&e.modal({backdrop:"static",keyboard:!1}),f&&"object"===typeof f&&$H(f).each(function(a){e.on(a.key,a.value)}));e.hasClass("in")||e.modal().show();return this},hideModalBox:function(){jQuery("#"+this.modalId).modal("hide")},getLoadingImg:function(){return new Element("span",{"class":"loading-img fa fa-refresh fa-5x fa-spin"})},
removeLoadingImg:function(){jQuery(".loading-img").remove()},loadUTCTime:function(a){var c;c=a.strip().split(" ");a=c[0].split("-");c=c[1].split(":");return new Date(Date.UTC(a[0],1*a[1]-1,a[2],c[0],c[1],c[2]))},observeClickNDbClick:function(a,c,b){$(a).observe("click",function(d){!0===$(a).retrieve("alreadyclicked")?($(a).store("alreadyclicked",!1),$(a).retrieve("alreadyclickedTimeout")&&clearTimeout($(a).retrieve("alreadyclickedTimeout")),"function"===typeof b&&b(d)):($(a).store("alreadyclicked",
!0),$(a).store("alreadyclickedTimeout",setTimeout(function(){$(a).store("alreadyclicked",!1);"function"===typeof c&&c(d)},300)))});return this},getUrlParam:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))},openInNewTab:function(a){window.open(a,"_blank").focus();return this},sleep:function(a,c){var b;for(b=(new Date).getTime();(new Date).getTime()<b+a;)"function"===
typeof c&&c((new Date).getTime());return this},ucfirst:function(a){return 0===a.length?a:a.charAt(0).toUpperCase()+a.slice(1)},_elTojQuery:function(a){a=a||null;if(null===a)return null;this._signRandID(a);return a=jQuery("#"+a.id)},_getNamesString:function(a,c,b){var d,f;d=c||"name";c=b||", ";b="";if(!Array.isArray(a))return b;f=[];a.each(function(a){"undefined"!==typeof a[d]&&f.push(a[d])});return b=f.join(c)},_disableAll:function(a,c){var b,d;b=c||"button,.btn,input,[save-item],[search_field],select,.select2";
d=(d=a||null)?this._elTojQuery(d):jQuery(document);"string"===typeof b&&""!==b.trim()&&d.find(b).prop("disabled",!0).attr("disabled",!0)}};