truncate `product`;
truncate `productinfo`;
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(1, 'California', '',  '2.8', '9348466000006', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (1, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(2, 'Teriyaki Chicken', '',  '2.8', '9348466000013', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (2, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(3, 'Cooked Tuna', '',  '2.8', '9348466000020', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (3, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(4, 'Salmon Avocado', '',  '2.8', '9348466000037', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (4, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(5, 'Vegetarian', '',  '2.8', '9348466000044', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (5, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(6, 'Cooked Prawn', '',  '2.8', '9348466000051', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (6, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(7, 'Prawn Tempura', '',  '2.8', '9348466000068', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (7, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(8, 'Katsu Chicken', '',  '2.8', '9348466000075', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (8, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(9, 'California', '',  '2.8', '9348466000112', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (9, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(10, 'Teriyaki Chicken', '',  '2.8', '9348466000129', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (10, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(11, 'Cooked Tuna', '',  '2.8', '9348466000136', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (11, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(12, 'Salmon Cucumber', '',  '2.8', '9348466000143', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (12, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(13, 'Cooked Prawn', '',  '2.8', '9348466000150', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (13, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(14, 'California Ura', '',  '9', '9348466001003', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (14, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(15, 'Teriyaki Chicken Ura', '',  '9.5', '9348466001010', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (15, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(16, 'Cooked Tuna Ura', '',  '9', '9348466001027', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (16, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(17, 'Salmon Ura', '',  '9', '9348466001034', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (17, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(18, 'Vegetarian Ura', '',  '9', '9348466001041', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (18, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(19, 'Cooked Prawn Ura', '',  '9', '9348466001058', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (19, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(20, 'Katsu Chicken Ura', '',  '9.5', '9348466001065', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (20, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(21, 'Quinoa T.Chicken', '',  '11.5', '9348466001409', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (21, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(22, 'Quinoa Tuna', '',  '11', '9348466001416', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (22, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(23, 'Quinoa Salmon', '',  '11', '9348466001423', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (23, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(24, 'Quinoa Katsu Chicken', '',  '11.5', '9348466001430', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (24, 2, '', 1, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(25, 'Salmon Sashimi', '',  '10', '9348466001072', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (25, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(26, 'Tuna Sashimi', '',  '11', '9348466001089', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (26, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(27, 'King Fish Sashimi', '',  '12', '9348466001096', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (27, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(28, 'Mixed Sashimi', '',  '12.5', '9348466001102', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (28, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(29, 'Salmon Nigiri', '',  '10', '9348466001119', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (29, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(30, 'Tuna Nigiri', '',  '11', '9348466001126', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (30, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(31, 'Prawn Nigiri', '',  '10', '9348466001133', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (31, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(32, 'Aburi Salmon', '',  '11', '9348466001140', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (32, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(33, 'Nigiri Combo', '',  '12', '9348466001157', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (33, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(34, 'King Fish Nigiri', '',  '12', '9348466001164', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (34, 2, '', 2, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(35, 'Seaweed Salad', '',  '5', '9348466003007', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (35, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(36, 'Ika Salad', '',  '6', '9348466003014', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (36, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(37, 'Prawn Gyoza', '',  '7', '9348466003021', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (37, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(38, 'Vege Gyoza', '',  '7', '9348466003038', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (38, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(39, 'Pork Gyoza', '',  '8', '9348466003052', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (39, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(40, 'Prawn Wrap', '',  '8', '9348466003069', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (40, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(41, 'Smoked Salmon Wrap', '',  '8', '9348466003076', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (41, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(42, 'Vegetable Wrap', '',  '8', '9348466003083', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (42, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(43, 'Chicken Wrap', '',  '8.5', '9348466003151', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (43, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(44, 'Seafood Salad', '',  '7.8', '9348466003168', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (44, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(45, 'Edamame', '',  '5', '9348466003175', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (45, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(46, 'Prawn Tempura (5pcs)', '',  '8.5', '9348466003205', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (46, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(47, 'Karaage Chicken (180g)', '',  '7.8', '9348466003182', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (47, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(48, 'Yasai Kakiage (3pcs)', '',  '6.5', '9348466003199', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (48, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(49, 'Vege Tempura (6pcs)', '',  '6.5', '9348466003212', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);    insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (49, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(50, 'Twin Pack', '',  '5.6', '9348466003267', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);  insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (50, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(51, 'Three Pack', '',  '8.4', '9348466003274', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (51, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(52, 'Four Pack', '',  '11.2', '9348466003281', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (52, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(53, 'Mini Chicken Salad', '',  '6', '9348466003304', '1', 'v1', '', 1, NOW(), 10, NOW(), 10);   insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (53, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);
insert into `product`(`id`, `name`, `description`, `unitPrice`, `barcode`, `usedByVariance`, `labelVersionNo`, `size`, `active`, `created`, `createdById`, `updated`, `updatedById`) values(54, 'Dynamite Roll', '',  '12.6', '9348466001607', '1', 'v1', '', 1, NOW(), 10, NOW(), 10); insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`) values (54, 2, '', 3, 'Category', 1, NOW(), 10, NOW(), 10);


insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`)
select pro.id, 3, 0, 0, 'Store', 1, NOW(), 10, NOW(), 10 from product pro;

insert into `productinfo` (`productId`, `typeId`, `value`, `entityId`, `entityName`, `active`, `created`, `createdById`, `updated`, `updatedById`)
select pro.id, 1, '', pro.id, 'Material', 1, NOW(), 10, NOW(), 10 from product pro;

truncate `material`;
insert into `material` (`id`, `name`, `description`, `active`, `created`, `createdById`, `updated`, `updatedById`)
select pro.id, pro.name, pro.description, 1, NOW(), 10, NOW(), 10 from product pro;

