var PageJs=new Class.create;
PageJs.prototype=Object.extend(new CRUDPageJs,{_getTitleRowData:function(){return{id:"ID",active:"Active",name:"Name",description:"Description",barcode:"Barcode",unitPrice:"Unit Price",size:"Size",categories:"Categories"}},_bindSearchKey:function(){var a;a=this;$("searchPanel").getElementsBySelector("[search_field]").each(function(d){d.observe("keydown",function(b){a.keydown(b,function(){$("searchBtn").click()})})});return this},loadSelect2:function(){var a,d;jQuery("select.select2").each(function(){a={};
if("Infinity"===$(this).readAttribute("data-minimum-results-for-search")||"infinity"===$(this).readAttribute("data-minimum-results-for-search")||-1==$(this).readAttribute("data-minimum-results-for-search"))a.minimumResultsForSearch="Infinity";jQuery(this).select2(a)});jQuery('[search_field="pro.categories"]').select2({allowClear:!0,multiple:!0,width:"100%",ajax:{delay:250,url:"/ajax/getAll",type:"GET",data:function(a){return{searchTxt:"name like ?",searchParams:["%"+a+"%"],entityName:"Category",pageNo:1}},
results:function(a,c,e){d=[];a.resultData&&a.resultData.items&&a.resultData.items.each(function(a){d.push({id:a.id,text:a.name,data:a})});return{results:d}}},cache:!0,escapeMarkup:function(a){return a}})},_getOjbNames:function(a){var d;d=[];a.each(function(a){d.push(a.name)});return jQuery.unique(d)},_getResultRow:function(a,d){var b,c,e;b=this;c=d||!1;e=!0===c?"strong":"span";return(new Element("span",{"class":"row"})).store("data",a).addClassName(!1===a.active&&!1===c?"warning":"").addClassName("list-group-item").addClassName("item_row").writeAttribute("item_id",
a.id).insert({bottom:(new Element(e,{"class":"name col-sm-3 col-xs-12"+(!0===c?"hidden-xs":"")})).update(!0===c?a.name:(new Element("div")).insert({bottom:(new Element("div")).update(a.name)}).insert({bottom:(new Element("div")).insert({bottom:(new Element("i")).update((new Element("small")).update(a.description))})}))}).insert({bottom:(new Element(e,{"class":"barcode col-sm-2 col-xs-12"+(!0===c?"hidden-xs":"")})).update(a.barcode)}).insert({bottom:(new Element(e,{"class":"unitPrice col-sm-2 col-xs-12"+
(!0===c?"hidden-xs":"")})).update(!0===c?a.unitPrice:b.getCurrency(a.unitPrice))}).insert({bottom:(new Element(e,{"class":"size col-md-1 hidden-sm col-xs-12"+(!0===c?"hidden-xs":"")})).update(a.size)}).insert({bottom:(new Element(e,{"class":"size col-sm-2 col-xs-12"+(!0===c?"hidden-xs":"")})).update(!0===c?a.categories:b._getOjbNames(a.categories).join(", "))}).insert({bottom:(new Element(e,{"class":"text-right btns col-sm-2 col-xs-12"})).update(!0===c?"":(new Element("span",{"class":"btn-group"})).insert({bottom:(new Element("span")).addClassName(!1===
a.active&&!1===c?"btn btn-success":"btn btn-info").writeAttribute("data-loading-text",'<i class="fa fa-refresh fa-spin"></i>').insert({bottom:(new Element("span")).addClassName(!1===a.active&&!1===c?"glyphicon glyphicon-repeat":"glyphicon glyphicon-print")}).observe("click",function(){b._printItem(this,a)})}).insert({bottom:(new Element("span",{"class":"btn btn-primary",title:"Edit"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",function(){b._openDetailsPage(a)})}).insert({bottom:(new Element("span")).addClassName(!1===
a.active&&!1===c?"btn btn-success":"btn btn-danger").writeAttribute("title",!1===a.active&&!1===c?"Re-activate":"De-activate").insert({bottom:(new Element("span")).addClassName(!1===a.active&&!1===c?"glyphicon glyphicon-repeat":"glyphicon glyphicon-trash")}).observe("click",function(){if(!confirm("Are you sure you want to "+(!0===a.active?"DE-ACTIVATE":"RE-ACTIVATE")+" this item?"))return!1;b._deleteItem(a,a.active)})}))})},_openDetailsPage:function(a){jQuery.fancybox({width:"95%",height:"95%",modal:!0,
autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,type:"iframe",href:"/product/"+(a?a.id:"new")+".html",helpers:{overlay:{locked:!1}},beforeClose:function(){}});return this},_openLabel:function(a){var d,b;d=$(a).retrieve("labelData");b=window.open("","","width=300,height=800,directories=no,titlebar=no,toolbar=no,location=no,status=no,menubar=no,scrollbars=no");if(!b)return this.showModalBox("<b>Window Popup Blocked</b>",'Your browser has blocked the popup from this site, Please change your browser settings to allow popup from this site and try again <span class="btn btn-xs btn-info" onclick="$(\''+
a.id+"').click();\"> here </span>. <div></b>"),this;b.document.write(d);b.document.close();b.focus();b.print();b.close();return this},_printItem:function(a,d){var b,c,e;b=this;b._signRandID(a);b.postAjax(b.getCallbackId("printLabel"),{id:d.id},{onLoading:function(){jQuery(a).button("loading")},onSuccess:function(d,g){try{(c=b.getResp(g,!1,!0))&&c.item&&(e=c.item,a.store("labelData",e),b._openLabel(a))}catch(h){b.showModalBox('<span class="text-danger">ERROR:</span>',h,!0),$(a).show()}},onComplete:function(){jQuery(a).button("reset")}});
return b},_updateItem:function(a,d,b,c){var e,f,g,h;e=this;d={itemId:$(a).up(".item_row[item_id]").readAttribute("item_id"),entityId:d,newValue:b,method:c};if(null!==d)return e.postAjax(e.getCallbackId("updateItem"),d,{onLoading:function(){$(a).hide()},onSuccess:function(b,c){try{(f=e.getResp(c,!1,!0))&&f.item&&(g=$(e.resultDivId).down("#"+e.resultDivId+"-body").down(".item_row[item_id="+f.item.id+"]"),h=e._getResultRow(f.item).addClassName("list-group-item").addClassName("item_row").writeAttribute("item_id",
f.item.id),g.replace(h))}catch(d){e.showModalBox('<span class="text-danger">ERROR:</span>',d,!0),$(a).show()}}}),e}});