var CRUDPageJs=new Class.create;
CRUDPageJs.prototype=Object.extend(new BPCPageJs,{resultDivId:"",searchDivId:"",totalNoOfItemsId:"",_pagination:{pageNo:1,pageSize:30},_searchCriteria:{},_nextPageColSpan:5,_titleRowData:{id:"ID",active:"Active",name:"Name",description:"Description",created:"Created",createdBy:"Created By",updated:"Updated",updatedBy:"Updated By"},setHTMLIds:function(b,e,a){this.resultDivId=b;this.searchDivId=e;this.totalNoOfItemsId=a;return this},_getTitleRowData:function(){return this._titleRowData},_bindSearchKey:function(){var b;
b=this;$("searchPanel").getElementsBySelector("[search_field]").each(function(e){e.observe("keydown",function(a){b.keydown(a,function(){$("searchBtn").click()})})});return b},getSearchCriteria:function(){var b,e;b=this;null===b._searchCriteria&&(b._searchCriteria={});e=!0;$(b.searchDivId).getElementsBySelector("[search_field]").each(function(a){b._searchCriteria[a.readAttribute("search_field")]=$F(a);if($F(a)instanceof Array&&0<$F(a).size()||"string"===typeof $F(a)&&!$F(a).blank())e=!1});!0===e&&
(b._searchCriteria=null);return b},_getResultRow:function(b,e){var a,c,d;a=this;c=e||!1;d=!0===c?"strong":"span";return(new Element("span",{"class":"row"})).store("data",b).addClassName(!1===b.active&&!1===c?"warning":"").addClassName("list-group-item").addClassName("item_row").writeAttribute("item_id",b.id).insert({bottom:(new Element(d,{"class":"name col-sm-7 col-xs-12"})).update(b.name)}).insert({bottom:(new Element(d,{"class":"description col-sm-3 col-xs-12"})).update(b.description)}).insert({bottom:(new Element(d,
{"class":"text-right btns col-sm-2 col-xs-12"})).update(!0===c?(new Element("span",{"class":"btn btn-primary btn-xs col-xs-12",title:"New"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-plus"})}).insert({bottom:" NEW"}).observe("click",function(){a._openDetailsPage()}):(new Element("span",{"class":"btn-group btn-group-xs"})).insert({bottom:(new Element("span",{"class":"btn btn-primary",title:"Delete"})).insert({bottom:new Element("span",{"class":"glyphicon glyphicon-pencil"})}).observe("click",
function(){a._openDetailsPage(b)})}).insert({bottom:(new Element("span")).addClassName(!1===b.active&&!1===c?"btn btn-success":"btn btn-danger").writeAttribute("title",!1===b.active&&!1===c?"Re-activate":"De-activate").insert({bottom:(new Element("span")).addClassName(!1===b.active&&!1===c?"glyphicon glyphicon-repeat":"glyphicon glyphicon-trash")}).observe("click",function(){if(!confirm("Are you sure you want to "+(!0===b.active?"DE-ACTIVATE":"RE-ACTIVATE")+" this item?"))return!1;a._deleteItem(b,
b.active)})}))})},loadSelect2:function(){var b;jQuery("select.select2").each(function(){b={};if("Infinity"===$(this).readAttribute("data-minimum-results-for-search")||"infinity"===$(this).readAttribute("data-minimum-results-for-search")||-1==$(this).readAttribute("data-minimum-results-for-search"))b.minimumResultsForSearch="Infinity";jQuery(this).select2(b)});return this},_openDetailsPage:function(b){jQuery.fancybox({width:"95%",height:"95%",modal:!0,autoScale:!1,autoDimensions:!1,fitToView:!1,autoSize:!1,
type:"iframe",href:"/"+this._focusEntity.toLowerCase()+"/"+(b?b.id:"new")+".html",helpers:{overlay:{locked:!1}}});return this},getResults:function(b,e){var a,c,d,f,g;a=this;c=b||!1;d=$(a.resultDivId);if("disabled"===jQuery("#"+pageJs.searchDivId+" #searchBtn").attr("disabled")||!0===jQuery("#"+pageJs.searchDivId+" #searchBtn").attr("disabled")||"true"===jQuery("#"+pageJs.searchDivId+" #searchBtn").attr("disabled"))return a;!0===c&&(a._pagination.pageNo=1);a._pagination.pageSize=e||a._pagination.pageSize;
a.postAjax(a.getCallbackId("getItems"),{pagination:a._pagination,searchCriteria:a._searchCriteria},{onCreate:function(){jQuery("#"+a.searchDivId+" #searchBtn").attr("disabled",!0).button("loading");!0===c&&d.update("").addClassName("list-group").insert({bottom:new Element("div",{"class":"container-fluid",id:a.resultDivId+"-head"})}).insert({bottom:new Element("div",{"class":"container-fluid",id:a.resultDivId+"-body"})}).insert({bottom:a.getLoadingImg()})},onSuccess:function(b,e){try{if(f=a.getResp(e,
!1,!0))$(a.totalNoOfItemsId).update(f.pageStats.totalRows),!0===c&&(d.down("#"+a.resultDivId+"-head").insert({bottom:a._getResultRow(a._getTitleRowData(),!0).addClassName("list-group-item").setStyle("font-weight: bold;")}),f.items&&0!==f.items.size()||d.insert({bottom:a.getAlertBox("Nothing found.","").addClassName("alert-warning")})),d.getElementsBySelector(".paginWrapper").each(function(a){a.remove()}),g=$(d).down("#"+a.resultDivId+"-body"),f.items.each(function(b){g.insert({bottom:a._getResultRow(b).addClassName("list-group-item").addClassName("item_row").writeAttribute("item_id",
b.id)})}),f.pageStats.pageNumber<f.pageStats.totalPages&&d.insert({bottom:a._getNextPageBtn().addClassName("paginWrapper")})}catch(l){d.insert({bottom:a.getAlertBox("Error",l).addClassName("alert-danger")})}},onComplete:function(){jQuery("#"+a.searchDivId+" #searchBtn").attr("disabled",!1).button("reset");d.getElementsBySelector(".loading-img").each(function(a){a.remove()});return a}});return a},_getNextPageBtn:function(){var b;b=this;return(new Element("tfoot")).insert({bottom:(new Element("tr")).insert({bottom:(new Element("td",
{colspan:b._nextPageColSpan,"class":"text-center"})).insert({bottom:(new Element("span",{"class":"btn btn-primary","data-loading-text":"Fetching more results ..."})).update("Show More").observe("click",function(){b._pagination.pageNo=1*b._pagination.pageNo+1;jQuery(this).button("loading");b.getResults()})})})})},_saveItem:function(b,e,a){var c,d,f,g,h;c=this;d=c._collectFormData(e,a);if(null!==d)return c.postAjax(c.getCallbackId("saveItem"),{item:d},{onCreate:function(){d.id&&e.addClassName("item_row").writeAttribute("item_id",
d.id);e.hide()},onSuccess:function(a,b){try{(f=c.getResp(b,!1,!0))&&f.item&&(g=$(c.resultDivId).down("#"+c.resultDivId+"-body").down(".item_row[item_id="+f.item.id+"]"),h=c._getResultRow(f.item).addClassName("item_row").writeAttribute("item_id",f.item.id),g?g.replace(h):($(c.resultDivId).down("tbody").insert({top:h}),e.remove(),$(c.totalNoOfItemsId).update(1*$(c.totalNoOfItemsId).innerHTML+1)))}catch(d){c.showModalBox('<span class="text-danger">ERROR:</span>',d,!0),e.show()}}}),c},_deleteItem:function(b,
e){var a,c,d,f;a=this;c=$(a.resultDivId).down("#"+a.resultDivId+"-body").down(".item_row[item_id="+b.id+"]");a.postAjax(a.getCallbackId("deleteItems"),{ids:[b.id],deactivate:!0===e},{onCreate:function(){c&&c.hide()},onSuccess:function(b,e){try{if(d=a.getResp(e,!1,!0))f=1*$(a.totalNoOfItemsId).innerHTML-1,$(a.totalNoOfItemsId).update(0>=f?0:f),c&&(d&&d.items&&Array.isArray(d.items)&&0<d.items.length?c.replace(a._getResultRow(d.items[0])):c.remove())}catch(k){a.showModalBox('<span class="text-danger">ERROR</span>',
k,!0),c&&c.show()}}});return a}});